global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: desktop_nanny
    static_configs:
      - targets:
          - nanny:8000
    metrics_path: /
    # In standalone (non-compose) mode, replace 'nanny' with 'localhost'
